set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(NOT DEFINED MINGW_TARGET_TRIPLE)
    set(MINGW_TARGET_TRIPLE x86_64-w64-mingw32)
endif()

find_program(MINGW_C_COMPILER ${MINGW_TARGET_TRIPLE}-gcc REQUIRED)
find_program(MINGW_CXX_COMPILER ${MINGW_TARGET_TRIPLE}-g++ REQUIRED)
find_program(MINGW_RC_COMPILER ${MINGW_TARGET_TRIPLE}-windres)

set(CMAKE_C_COMPILER ${MINGW_C_COMPILER})
set(CMAKE_CXX_COMPILER ${MINGW_CXX_COMPILER})

if(MINGW_RC_COMPILER)
    set(CMAKE_RC_COMPILER ${MINGW_RC_COMPILER})
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
